### ISSUE TITLE
Unable to download Rhubarb in-app

### ISSUE THREAD

**Issue by dimitritholen** [steveway/papagayo-ng#39]
Using Papagayo-NG 1.6.6.0

When I click "Download Rhubarb" in the toolbar, I get the following error:

```
Traceback (most recent call last):
  File "utilities.py", line 196, in run
  File "LipsyncFrameQT.py", line 473, in download_rhubarb
  File "urllib\request.py", line 214, in urlopen
  File "urllib\request.py", line 501, in open
  File "urllib\request.py", line 320, in __init__
  File "urllib\request.py", line 346, in full_url
  File "urllib\request.py", line 375, in _parse
ValueError: unknown url type: ''
```

**Comment by steveway** [comment]
I see, this happens because we are looking for specific file endings depending on the architecture:
```
if platform.system() == "Darwin":
    if download["name"].endswith("-osx.zip"):
        release_url = download["browser_download_url"]
    else:
        if download["name"].endswith("-win32.zip"):
            release_url = download["browser_download_url"]
```
Apparently they changed it so it now ends with "-macOS.zip" for macOS and "-Windows.zip" for Windows.
I've updated the code in my branch, this is untested but if that is the only change it should work:
https://github.com/steveway/papagayo-ng/blob/master/LipsyncFrameQT.py
